name: Container Vulnerability Scan

on:
  push:
    paths:
      - 'Dockerfiles/**'
      - '.github/workflows/scan.yml'
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker image
      run: |
        docker build -t base-image ./Dockerfiles/base

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: base-image
        scan-type: image
        format: table
        exit-code: 0
        output: scans/trivy/base.txt

    - name: Upload Trivy results
      uses: actions/upload-artifact@v3
      with:
        name: trivy-results
        path: scans/trivy/
